# Generated by Django 3.2 on 2021-05-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='highestBid',
            new_name='startingBid',
        ),
    ]
