# Generated by Django 3.2 on 2021-05-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='startingBid',
        ),
    ]
