# Generated by Django 3.2 on 2021-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
