# Generated by Django 3.2 on 2021-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
